### PR TITLE
Cart-sign in fixes

### PR DESCRIPTION
**Pull request by brzezin0**
1.While fetching the user cart, I encountered an endless loop issue. To resolve it I added the @JsonBackReference annotation in the LoginDto file (is it ok?).
2. Pls review the changes and let me know if everything is implemented correctly or if further adjustments are needed

### CODE REVIEW

**Comment by WiktoriaKrzyzanska** [comment]
I'm starting the review

**Comment by WiktoriaKrzyzanska** [comment]
Why use & instead of - in a branch name? & makes branch harder to pull as it's escape character

**Comment by brzezin0** [comment]
> Why use & instead of - in a branch name? & makes branch harder to pull as it's escape character 

Pardon, changed it a moment ago

**Comment by WiktoriaKrzyzanska** [comment]
The change on backend doesn't fix anything. It just made us unable to sign in

**Comment by brzezin0** [comment]
> The change on backend doesn't fix anything. It just made us unable to sign in 
> 

it fixed the problem with endless loop while trying to fetch a cart - I will send you video with my screen later and we can discuss it (maybe i made a mistake somewhere)

**Comment by WiktoriaKrzyzanska** [comment]
This code doesn't work

**Comment by MoonGuyPro** [comment]
ok

**Pull request merged**
